### ISSUE TITLE
Alpine linux Pure FTPD package does not include Ldap

### ISSUE THREAD

**Issue by ipetepete** [gimoh/docker-pureftpd#5]
Here's the build file: https://git.alpinelinux.org/cgit/aports/tree/testing/pure-ftpd/APKBUILD

Trying to use ldap as auth service results in this:
     
     + exec /usr/sbin/pure-ftpd -l ldap:/etc/pureftpd/ldap.conf -E -l puredb:/etc/pureftpd/passwd.pdb -j
     + /usr/local/sbin/syslog-stdout
     421 Unknown authentication method: ldap:/etc/pureftpd/ldap.conf

**Comment by gimoh** [comment]
I think the idea is that the package should be very minimal, which is actually also what I needed for my use case, as minimal as possible.

I'd say if you need this it'd be better to submit a request to [alpine bug tracker](https://bugs.alpinelinux.org/projects/alpine/issues) and request a separate version of pure-ftpd package that isn't minimal (maybe `pure-tfpd-full`?)

**Comment by gimoh** [comment]
FYI, I opened a [request for another pure-ftpd package including LDAP support](https://bugs.alpinelinux.org/issues/7948).
